### ISSUE TITLE
Error with radiant_window()

### ISSUE THREAD

**Issue by Simon2310** [radiant-rstats/radiant#142]
Hi,

I have the following error with radiant::radiant_window() :

Error in .Call("rs_shinyviewer", url, getwd(), 3) : 
  Nombre d'arguments incorrect (3), attendu 4 pour 'rs_shinyviewer'

How can I solve this?

I thank you in advance,

S B

**Comment by vnijs** [comment]
Thanks for reporting! I just pushed a fix to radiant.data on github. Please try it out.

**Comment by Simon2310** [comment]
Thanks for you answer. I updated radiant with radiant.update, but I am still having the same error. Do I need to do Something else?

**Comment by vnijs** [comment]
Try the below.

```
install.packages("remotes")
remotes::install_github("radiant-rstats/radiant.data", upgrade = "never")
```

**Comment by Simon2310** [comment]
Thanks! I have another error with the magrittr package. But it is due to the fact it has been compiled with R 3.6.3 and I am using R 3.6.2. So this is not related to this issue.

**Comment by Simon2310** [comment]
for more details, if needed:
Error: package or namespace load failed for 'lubridate' in library.dynam(lib, package, package.lib):
 DLL 'Rcpp' not found: maybe not installed for this architecture?

**Comment by vnijs** [comment]
What is your OS?

**Comment by Simon2310** [comment]
Hi!

I am on Windows 10, but using a portable version of R.

**Comment by vnijs** [comment]
What does "using a portable version of R." mean? Can you install the Rcpp package? That is the error I'm seeing.

https://cran.r-project.org/web/packages/Rcpp/index.html

**Comment by Simon2310** [comment]
I mean a portable application (that can be used on a portable storage device for instance). This is the case for my R and Rstudio.
Installing Rcpp was fine.

**Comment by Simon2310** [comment]
After uninstalling and reinstalling Rcpp, I am now able to update radiant.data, and the issue is solved. Thank you so much for your help!
